### ISSUE TITLE
The response to the `/api/game/start` route is not modified.

### ISSUE THREAD

**Issue by pierre42100** [lernejo/korekto-java-api-grader#4]
Hello, its me again (sorry). I might have found another (last) issue with the grader, in the class `NavyProxy`, in this method:

```java
 private void forwardPostRequestAndRespond(HttpExchange exchange, String originalBody) throws IOException {
            Optional<NavyApiClient.GameServerInfo> gameServerInfo = NavyApiClient.GameServerInfo.parse(originalBody);
            String body = gameServerInfo.isPresent() ? gameServerInfo.get().withPort(returnPort).toJson() : originalBody;
            try {
                HttpResponse<String> response = forwardRequest(exchange, b -> b.POST(HttpRequest.BodyPublishers.ofString(body)).build());
                recordAndRespond(exchange, originalBody, response);
            } catch (InterruptedException e) {
                throw new RuntimeException("Interrupted server thread", e);
            }
        }
```
In this function, the request that is forwarded to the standalone server is correctly modified : the url ot the server is modified with the `withPort` method to make further requests from the standalone server handled by the proxy. 

Unfortunately, it seems that the response to the request does not receive the same treatment : it is redirected as is to the client.

If the code of the secondary client rely on the url provided in the response of the route  `/api/game/start` to send further requests, the grader will not be able to record the requests, and an error will be thrown in the part 9 of the grader.

I think there are two possible workaround to this problem : we could either:
* Add more fields to the `CallHandler` class and modify the response of the standalone server to make it return the proxy port in its response.
* Explicity specify on the subject that the url provided in the response to the route is not reliable...

**Comment by ledoyen** [comment]
Hi, I for now I will modify the response as well so that the use of the arbiter proxy is transparent for instances of the exercise.
